### ISSUE TITLE
Support sort query parameter

### ISSUE THREAD

**Issue by mwawrusch** [codedoctor/hapi-routes-users#10]

**Comment by hisabimbola** [comment]
Any update on this feature? I am thinking of working to support filter and sort.

I will like to know if this feature is in progress

**Comment by mwawrusch** [comment]
Hi there. Sorry for the late reply, my github notifications somehow end up in spam. Right now I have zero time to change this. In case you want to supply a pull request I would suggest to have two parameters, sort and query, which basically allow for passing through of mongodb style parameters. I am pretty sure there is some module out there that handles that in a robust fashion. Feel free to supply a pull request.

**Comment by hisabimbola** [comment]
Thanks for your suggestions.

1. For the sort feature, yes we can just add another parameter that user can pass in for sorting.
2. For mongodb query, Jason and I found this [module](https://www.npmjs.com/package/mongo-querystring) on npm that create a standard for writing mongodb queries in the url and parses it to mongoDB query object.

What do you think about this @mwawrusch?

**Comment by mwawrusch** [comment]
That's an awesome find, definitely use that.

**Comment by hisabimbola** [comment]
Ok, I will implement this and submit a PR in few hours time.
